# GROUP THE ALERTS BY TIMESTAMP, SERVER AND ALERT TYPE AND GET THE COUNT

In [29]:
import pandas as pd

data = {
    'timestamp': ['2023-10-21 08:15:00', '2023-10-21 08:30:00', '2023-10-21 09:15:00', '2023-10-21 09:45:00'],
    'server': ['A', 'A', 'B', 'A'],
    'alert_type': ['Warning', 'Warning', 'Error', 'Warning']
}

df = pd.DataFrame(data)
df['timestamp'] = pd.to_datetime(df['timestamp'])  # Convert the 'timestamp' column to datetime format

# Round the 'timestamp' column to the next hour
df['timestamp'] = df['timestamp'] + pd.DateOffset(hours=1)
df['timestamp'] = df['timestamp'].dt.floor('H')

# Group by 'timestamp', 'server', and 'alert_type', then count the occurrences
result = df.groupby(['timestamp', 'server', 'alert_type']).size().reset_index(name='count')

# Display the result
print(result)

            timestamp server alert_type  count
0 2023-10-21 09:00:00      A    Warning      2
1 2023-10-21 10:00:00      A    Warning      1
2 2023-10-21 10:00:00      B      Error      1

# GENERATE AN HOURLY TIMESTAMP FOR EACH SERVER

In [5]:
import pandas as pd

# Define the start and end timestamps
start_timestamp = '2023-10-21 08:00:00'
end_timestamp = '2023-10-21 12:00:00'

# Define the list of servers
servers = ['Server1', 'Server2', 'Server 3']  # Add more servers as needed

# Create a date range with hourly intervals
timestamps = pd.date_range(start=start_timestamp, end=end_timestamp, freq='H')

# Create a list of timestamps for each server
server_timestamps = []

for timestamp in timestamps:
    server_timestamps.extend([timestamp] * len(servers))

# Create a DataFrame with server and timestamp columns
data = {
    'server': servers * len(timestamps),
    'timestamp': server_timestamps
}

timestamp_df = pd.DataFrame(data)

# Display the generated timestamps for each server
print(timestamp_df)

      server           timestamp
0    Server1 2023-10-21 08:00:00
1    Server2 2023-10-21 08:00:00
2   Server 3 2023-10-21 08:00:00
3    Server1 2023-10-21 09:00:00
4    Server2 2023-10-21 09:00:00
5   Server 3 2023-10-21 09:00:00
6    Server1 2023-10-21 10:00:00
7    Server2 2023-10-21 10:00:00
8   Server 3 2023-10-21 10:00:00
9    Server1 2023-10-21 11:00:00
10   Server2 2023-10-21 11:00:00
11  Server 3 2023-10-21 11:00:00
12   Server1 2023-10-21 12:00:00
13   Server2 2023-10-21 12:00:00
14  Server 3 2023-10-21 12:00:00

# GENERATE AN HOURLY TIMESTAMP FOR EACH ALERT TYPE FOR EVERY SERVER

In [11]:
import pandas as pd

# Define the start and end timestamps
start_timestamp = '2023-10-21 08:00:00'
end_timestamp = '2023-10-21 12:00:00'

# Define the list of servers and alert types
servers = ['Server1', 'Server2']  # Add more servers as needed
alert_types = ['Alert1', 'Alert2']  # Add more alert types as needed

# Create a date range with hourly intervals
timestamps = pd.date_range(start=start_timestamp, end=end_timestamp, freq='H')

# Create a list of timestamps for each server and alert type combination
data = {
    'server': [],
    'alert': [],
    'timestamp': []
}

for timestamp in timestamps:
    for server in servers:
        for alert_type in alert_types:
            data['server'].append(server)
            data['alert'].append(alert_type)
            data['timestamp'].append(timestamp)

# Create a DataFrame with 'server', 'alert', and 'timestamp' columns
timestamp_df = pd.DataFrame(data)

# Display the generated timestamps for each server and alert type combination
print(timestamp_df)

     server   alert           timestamp
0   Server1  Alert1 2023-10-21 08:00:00
1   Server1  Alert2 2023-10-21 08:00:00
2   Server2  Alert1 2023-10-21 08:00:00
3   Server2  Alert2 2023-10-21 08:00:00
4   Server1  Alert1 2023-10-21 09:00:00
5   Server1  Alert2 2023-10-21 09:00:00
6   Server2  Alert1 2023-10-21 09:00:00
7   Server2  Alert2 2023-10-21 09:00:00
8   Server1  Alert1 2023-10-21 10:00:00
9   Server1  Alert2 2023-10-21 10:00:00
10  Server2  Alert1 2023-10-21 10:00:00
11  Server2  Alert2 2023-10-21 10:00:00
12  Server1  Alert1 2023-10-21 11:00:00
13  Server1  Alert2 2023-10-21 11:00:00
14  Server2  Alert1 2023-10-21 11:00:00
15  Server2  Alert2 2023-10-21 11:00:00
16  Server1  Alert1 2023-10-21 12:00:00
17  Server1  Alert2 2023-10-21 12:00:00
18  Server2  Alert1 2023-10-21 12:00:00
19  Server2  Alert2 2023-10-21 12:00:00

# GET THE HOURLY COUNT OF EACH ALERT TYPE IN EVERY SERVER

In [15]:
import pandas as pd

# Create the first dataframe (df1)
df1 = {
    'timestamp': ['2023-10-21 09:00:00', '2023-10-21 10:00:00', '2023-10-21 10:00:00'],
    'server': ['A', 'A', 'B'],
    'alert type': ['Warning', 'Warning', 'Error'],
    'count': [2, 1, 1]
}

df1 = pd.DataFrame(df1)

# Create the second dataframe (df2)
df2 = {
    'timestamp': ['2023-10-21 09:00:00', '2023-10-21 09:00:00', '2023-10-21 09:00:00', '2023-10-21 09:00:00',
                 '2023-10-21 10:00:00', '2023-10-21 10:00:00', '2023-10-21 10:00:00', '2023-10-21 10:00:00'],
    'server': ['A', 'A', 'B', 'B', 'A', 'A', 'B', 'B'],
    'alert type': ['Warning', 'Error', 'Warning', 'Error', 'Warning', 'Error', 'Warning', 'Error']
}

df2 = pd.DataFrame(df2)

# Merge the two dataframes on 'timestamp', 'server', and 'alert type', and fill missing count values with 0
result = df2.merge(df1, on=['timestamp', 'server', 'alert type'], how='left')
result['count'] = result['count'].fillna(0).astype(int)

# Display the modified df2
print(result)

             timestamp server alert type  count
0  2023-10-21 09:00:00      A    Warning      2
1  2023-10-21 09:00:00      A      Error      0
2  2023-10-21 09:00:00      B    Warning      0
3  2023-10-21 09:00:00      B      Error      0
4  2023-10-21 10:00:00      A    Warning      1
5  2023-10-21 10:00:00      A      Error      0
6  2023-10-21 10:00:00      B    Warning      0
7  2023-10-21 10:00:00      B      Error      1

# TESTING

In [28]:
import pandas as pd

data = {
    'timestamp': ['2023-10-21 08:15:00', '2023-10-21 08:30:00', '2023-10-21 09:15:00', '2023-10-21 09:45:00'],
    'server': ['A', 'A', 'B', 'A'],
    'alert_type': ['Warning', 'Warning', 'Error', 'Warning']
}

df = pd.DataFrame(data)
df['timestamp'] = pd.to_datetime(df['timestamp'])  # Convert the 'timestamp' column to datetime format

# Round the 'timestamp' column to the next hour
df['timestamp'] = df['timestamp'] + pd.DateOffset(hours=1)
df['timestamp'] = df['timestamp'].dt.floor('H')

# Group by 'timestamp', 'server', and 'alert_type', then count the occurrences
df = df.groupby(['timestamp', 'server', 'alert_type']).size().reset_index(name='count')
df

            timestamp server alert_type  count
0 2023-10-21 09:00:00      A    Warning      2
1 2023-10-21 10:00:00      A    Warning      1
2 2023-10-21 10:00:00      B      Error      1

In [29]:
# Define the start and end timestamps
start_timestamp = '2023-10-21 08:00:00'
end_timestamp = '2023-10-21 12:00:00'

# Define the list of servers and alert types
servers = df['server'].unique().tolist()
alert_types = df['alert_type'].unique().tolist()

# Create a date range with hourly intervals
timestamps = pd.date_range(start=start_timestamp, end=end_timestamp, freq='H')

# Create a list of timestamps for each server and alert type combination
data = {
    'timestamp': [],
    'server': [],
    'alert_type': []
}

for timestamp in timestamps:
    for server in servers:
        for alert_type in alert_types:
            data['server'].append(server)
            data['alert_type'].append(alert_type)
            data['timestamp'].append(timestamp)

# Create a DataFrame with 'server', 'alert', and 'timestamp' columns
df2 = pd.DataFrame(data)
df2

             timestamp server alert_type
0  2023-10-21 08:00:00      A    Warning
1  2023-10-21 08:00:00      A      Error
2  2023-10-21 08:00:00      B    Warning
3  2023-10-21 08:00:00      B      Error
4  2023-10-21 09:00:00      A    Warning
5  2023-10-21 09:00:00      A      Error
6  2023-10-21 09:00:00      B    Warning
7  2023-10-21 09:00:00      B      Error
8  2023-10-21 10:00:00      A    Warning
9  2023-10-21 10:00:00      A      Error
10 2023-10-21 10:00:00      B    Warning
11 2023-10-21 10:00:00      B      Error
12 2023-10-21 11:00:00      A    Warning
13 2023-10-21 11:00:00      A      Error
14 2023-10-21 11:00:00      B    Warning
15 2023-10-21 11:00:00      B      Error
16 2023-10-21 12:00:00      A    Warning
17 2023-10-21 12:00:00      A      Error
18 2023-10-21 12:00:00      B    Warning
19 2023-10-21 12:00:00      B      Error

In [31]:
# Merge the two dataframes on 'timestamp', 'server', and 'alert type', and fill missing count values with 0
result = df2.merge(df, on=['timestamp', 'server', 'alert_type'], how='left')
result['count'] = result['count'].fillna(0).astype(int)
result

             timestamp server alert_type  count
0  2023-10-21 08:00:00      A    Warning      0
1  2023-10-21 08:00:00      A      Error      0
2  2023-10-21 08:00:00      B    Warning      0
3  2023-10-21 08:00:00      B      Error      0
4  2023-10-21 09:00:00      A    Warning      2
5  2023-10-21 09:00:00      A      Error      0
6  2023-10-21 09:00:00      B    Warning      0
7  2023-10-21 09:00:00      B      Error      0
8  2023-10-21 10:00:00      A    Warning      1
9  2023-10-21 10:00:00      A      Error      0
10 2023-10-21 10:00:00      B    Warning      0
11 2023-10-21 10:00:00      B      Error      1
12 2023-10-21 11:00:00      A    Warning      0
13 2023-10-21 11:00:00      A      Error      0
14 2023-10-21 11:00:00      B    Warning      0
15 2023-10-21 11:00:00      B      Error      0
16 2023-10-21 12:00:00      A    Warning      0
17 2023-10-21 12:00:00      A      Error      0
18 2023-10-21 12:00:00      B    Warning      0
19 2023-10-21 12:00:00      B      Error      0